send_email: False
use_transmission: False
store_torrent_files: False

transmission:
  address: localhost
  port: 9091
  user: admin
  password: admin

email:
  from: *****
  to: *****
  subject: New torrents from Lostfilm
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_username: ****
  smtp_password: ****
  smtp_tls: yes

lostfilm:
  feed: http://www.lostfilm.tv/rssdd.xml
  cookie: " uid=****; pass=****; usess=****"

user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0

downloads-path: /path/to/downloads/dir/
torrents-path: /path/to/torrents/dir/

series:
  720p:
    - Bitten:
       path: Serials
  1080p:
    - Cougar Town:
        alternate_name: 'Город хищниц'
  MP4:
    - Grimm
    - Stargate Atlantis